### ISSUE TITLE
Error: options.url required

### ISSUE THREAD

**Issue by alexpilugin** [brianleroux/tiny-json-http#13]
> Error:  Error: options.url required
    at Error (native)
    at Object.module.exports [as get] (/Developer/tiny-promiss/node_modules/tiny-json-http/bundle.js:1:1000)
    at Promise (/Developer/Nodejs/2018.02.05 node-quering/010-tiny-promiss/index.js:31:30)
    at getData (/Developer/Nodejs/2018.02.05 node-quering/010-tiny-promiss/index.js:29:12)
    at Object.<anonymous> (/Developer/Nodejs/2018.02.05 node-quering/010-tiny-promiss/index.js:15:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

```
'use strict';

var tiny = require('tiny-json-http')

const url =
    "https://maps.googleapis.com/maps/api/geocode/json?address=Florence";

getData(url)
    .then(data =>
        console.log(
            `City: ${data.results[0].formatted_address} -`,
            `Latitude: ${data.results[0].geometry.location.lat} -`,
            `Longitude: ${data.results[0].geometry.location.lng}`
        )
    )
    .catch(error => {
        console.log('Error: ', error);
    });

function getData(url) {
    // return new pending promise
    return new Promise((resolve, reject) => {

        const request = tiny.get(url, (err, response) => {
            if (err) {
                console.log('Error', err);
                reject(err);
            } else {
                const body = response.body;
                console.log(body);
                resolve(body);
            }
        });
    })
}
```

**Comment by neurotech** [comment]
Try wrapping the `url` portion of `const request = tiny.get(url, (err, response) => {` in curly braces `{}`:

```js
'use strict';

var tiny = require('tiny-json-http')

const url =
    "https://maps.googleapis.com/maps/api/geocode/json?address=Florence";

getData(url)
    .then(data =>
        console.log(
            `City: ${data.results[0].formatted_address} -`,
            `Latitude: ${data.results[0].geometry.location.lat} -`,
            `Longitude: ${data.results[0].geometry.location.lng}`
        )
    )
    .catch(error => {
        console.log('Error: ', error);
    });

function getData(url) {
    // return new pending promise
    return new Promise((resolve, reject) => {

        const request = tiny.get({url}, (err, response) => {
            if (err) {
                console.log('Error', err);
                reject(err);
            } else {
                const body = response.body;
                console.log(body);
                resolve(body);
            }
        });
    })
}
```

**Comment by alexpilugin** [comment]
Oh! Thank you. It works!

**Comment by neurotech** [comment]
My pleasure - basically the module is expecting the `url` to be part of an object, but you were passing it through as a string.

**Comment by brianleroux** [comment]
Hey @alexpilugin ! Just FYI that `tiny-json-http` "natively" supports `Promise`. If you don't supply a callback it'll return one for you. 

Ex.
```javascript
var tiny = require('tiny-json-http')
var url = 'https://maps.googleapis.com/maps/api/geocode/json?address=Florence'

function handler(data) {
  var first = data.body.results[0]
  console.log(
    `City: ${first.formatted_address} -`, 
    `Latitude: ${first.geometry.location.lat} -`,
    `Longitude: ${first.geometry.location.lng}`
  )
}

tiny.get({url}).then(handler).catch(console.log)
```

**Comment by alexpilugin** [comment]
Hi @brianleroux 

Your version looks amazing but from first time I received:   
```
TypeError: Cannot read property 'formatted_address' of undefined
    at handler (/011-tiny-callback/index.js:18:23)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```
from second launch: $ node index.js it produced an expected result!

**Comment by brianleroux** [comment]
bizarre! was unable to repro that myself

<img width="741" alt="screen shot 2018-02-09 at 2 16 00 pm" src="https://user-images.githubusercontent.com/990/36052758-d6801b2a-0da3-11e8-8fff-84e9e91517cc.png">

**Comment by alexpilugin** [comment]
@brianleroux Yes, it was only once. Sorry, I couldn't replicate this error as well.

**Comment by brianleroux** [comment]
np at all! lmk if you run into anything else or have any other questions. happy to help. 🙏
