### ISSUE TITLE
Follow HTTP redirects

### ISSUE THREAD

**Issue by ryanblock** [brianleroux/tiny-json-http#20]
Presently, accessing a url that responds with a redirect results in an error.

Similar to `curl -L {url}`, imo tiny should have an option that follows `301` + `302` redirects.

**Comment by hovissimo** [comment]
This is particularly painful because the Enhance docs suggest using tiny-json-http for request tests, but the default APIs generated for Enhance respond to successful POSTs with a 302.

See https://enhance.dev/docs/learn/practices/testing

Example test after running `begin generate scaffold User name:string email:string`
```javascript
test('create new user', async (t) => {         
  t.plan(3)                                    
  const user = {                               
    name: 'Guy',                               
    email: 'guy@onabuffalo.com',               
  }                                            
  const response = await tiny.post({           
    url: url('/users/'),                       
    data: user,                                
  })                                           
  t.equal(user.name, response.body.user.name)  
  t.equal(user.email, response.body.user.email)
  t.ok(response.body.user.key)                 
  t.end()                                      
})                                             
```

**Comment by ryanblock** [comment]
Thanks @hovissimo! Just updated the Enhance Discord re. the release of 7.5 (which no longer errors on 301/2). I think we can close this for now!

**Comment by hovissimo** [comment]
Tahnk you!
