### ISSUE TITLE
accessing the result outside the callback function

### ISSUE THREAD

**Issue by alias-rahil** [brianleroux/tiny-json-http#23]
`var tiny = require('tiny-json-http')`
`var url = 'http://www.randomkittengenerator.com'`

`tiny.get({url}, function _get(err, result) {`
  `if (err) {`
    `console.log('ruh roh!', err)`
 ` }`
  `else {`
    `console.log(result)`
`  }`
`})`

How do I access the result outside the callback function? I want to return it elsewhere.

**Comment by brianleroux** [comment]
try this out!

```javascript
var tiny = require('tiny-json-http')
var url = 'http://www.randomkittengenerator.com'

try {
  let result = await tiny.get({url}
  console.log(result)
}
catch(err) {
  console.log('ruh roh!', err)
}
```

**Comment by alias-rahil** [comment]
Thanks!
