### ISSUE TITLE
'Cannot Find HTTP'

### ISSUE THREAD

**Issue by SamKomesarook** [brianleroux/tiny-json-http#38]
Hi!

I am running node v19.1.0, and have installed your lib to be used in a Next.js project. It throws an error when imported into a page while running dev mode:

`Error: Cannot find module 'http'`

I am importing it as `import tiny from "tiny-json-http"`

Strangely, when used during a build for dynamic route loading, it works fine... I have tried removing _node-modules_ and reinstalling, to no avail.

**Comment by ryanblock** [comment]
This is probably something related to Next and/or v19, or if you're bundling, that. [`http` is a Node.js module](https://nodejs.org/api/http.html). Try without Next and without bundling!
