### ISSUE TITLE
dotenv removed during package installation

### ISSUE THREAD

**Issue by FiskPay** [brianleroux/tiny-json-http#40]
Hello!
I have just got this package and i got this message:

>>added 1 package, and audited 339 packages in 2s

It turns out that the package that got removed was dotenv.
Is it just me? Should this happen, for a reason?

**Comment by ryanblock** [comment]
I don't know what's going on here, but it's not related to this package. As you can see from the package.json, there are no dependencies and no postinstall scripts.
