### ISSUE TITLE
Set automatically the header Content-Length

### ISSUE THREAD

**Issue by magiksd** [brianleroux/tiny-json-http#9]
Hi,

Some API requires that the header "Content-Length" is set in order to work, if not the HTTP status 411 (Length Required) is returned. When using your module, we have to specify it manually for each request, and it's very annoying when using JSON data because we have to stringify it to get the length but can't use the stringified data as parameter because you'll stringify it again.

In _write.js ([line 42](https://github.com/brianleroux/tiny-json-http/blob/master/_write.js#L42)), you could simply add the following code :
```
opts.headers['Content-Length'] = postData.length
```

**Comment by brianleroux** [comment]
Good call.

**Comment by brianleroux** [comment]
Thx! published in `tiny-json-http@5.3.2` 🔥
